# Turns a binary file into a C array plus a header, the way rt64's `file_to_c`
# tool does. Done in CMake rather than with that tool so the recompiled
# libraries can be built without configuring rt64 -- this is the only thing
# Goemon64Recomp needed file_to_c for on this path.
#
#   cmake -DINPUT=<bin> -DSYMBOL=<name> -DOUT_C=<c> -DOUT_H=<h> -P embed_binary.cmake

if(NOT DEFINED INPUT OR NOT DEFINED SYMBOL OR NOT DEFINED OUT_C OR NOT DEFINED OUT_H)
    message(FATAL_ERROR "embed_binary.cmake needs INPUT, SYMBOL, OUT_C and OUT_H")
endif()

file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" hex_len)
math(EXPR byte_count "${hex_len} / 2")

# "0a1b2c" -> "0x0a,0x1b,0x2c,"
string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
# Wrap so the generated file is not one enormous line.
string(REGEX REPLACE "(([^,]+,){16})" "\\1\n    " bytes "${bytes}")

get_filename_component(out_h_name "${OUT_H}" NAME)

file(WRITE "${OUT_C}"
"/* Generated by cmake/embed_binary.cmake from ${INPUT}. Do not edit. */\n"
"#include \"${out_h_name}\"\n"
"\n"
"unsigned char ${SYMBOL}[${byte_count}] = {\n    ${bytes}\n};\n")

file(WRITE "${OUT_H}"
"/* Generated by cmake/embed_binary.cmake. Do not edit. */\n"
"#ifndef ${SYMBOL}_H\n"
"#define ${SYMBOL}_H\n"
"\n"
"#ifdef __cplusplus\n"
"extern \"C\" {\n"
"#endif\n"
"\n"
"extern unsigned char ${SYMBOL}[${byte_count}];\n"
"\n"
"#ifdef __cplusplus\n"
"}\n"
"#endif\n"
"\n"
"#endif\n")
